from PIL import Image
from numpy import *
from scipy.ndimage import filters
from matplotlib.pylab import *
def Sobel():
    im=array(Image.open('test.jpg').convert('L'))
    imx=zeros(im.shape)
    filters.sobel(im,1,imx)
    imy=zeros(im.shape)
    filters.sobel(im,1,imy)
    magnitude=sqrt(imx**2+imy**2)
    set_cmap('gray')
    subplot(141)
    axis('off')
    imshow(im)
    subplot(142)
    axis('off')
    imshow(imx)
    subplot(143)
    axis('off')
    imshow(imy)
    subplot(144)
    axis('off')
    imshow(magnitude)
def Gauss():
    im = array(Image.open('test.jpg').convert('L'))
    imx = zeros(im.shape)
    imy = zeros(im.shape)
    filters.gaussian_filter(im,(1,1),(0,1),imx)
    filters.gaussian_filter(im,(1,1),(1,0),imy)
    set_cmap('gray')
    subplot(131)
    axis('off')
    imshow(im)
    subplot(132)
    axis('off')
    imshow(imx)
    subplot(133)
    axis('off')
    imshow(imy)
